# Generated by Django 3.0.1 on 2020-10-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('publish', models.BooleanField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True, null=True)),
                ('modification_date', models.DateTimeField(blank=True, null=True)),
                ('unpublish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True, null=True)),
                ('orders_status_cocina', models.BooleanField(blank=True, default=False, null=True)),
                ('orders_status_barra', models.BooleanField(blank=True, default=False, null=True)),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesa', to='inventary.Mesa')),
            ],
        ),
        migrations.CreateModel(
            name='PreparationSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('allergy', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('publish', models.BooleanField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True, null=True)),
                ('modification_date', models.DateTimeField(blank=True, null=True)),
                ('unpublish_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventary.Category')),
                ('preparation_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparation_site', to='inventary.PreparationSite')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True, null=True)),
                ('order_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='inventary.Orders')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventary.Product')),
            ],
        ),
    ]
