# Generated by Django 3.0.1 on 2020-10-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0002_orders_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('calle', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.PositiveIntegerField()),
                ('portal', models.PositiveIntegerField()),
                ('piso', models.PositiveIntegerField()),
                ('puerta', models.PositiveIntegerField()),
            ],
        ),
    ]
