# Generated by Django 3.0.1 on 2020-10-17 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0003_auto_20201016_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersproducts',
            name='mesa',
        ),
        migrations.AddField(
            model_name='orders',
            name='mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesa', to='inventary.Mesa'),
        ),
    ]
