# Generated by Django 3.0.1 on 2020-09-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0003_auto_20200930_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unpublish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
