# Generated by Django 3.0.1 on 2020-10-01 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0011_orders_ordersproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersproducts',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='inventary.Orders'),
        ),
    ]
