# Generated by Django 3.0.1 on 2020-10-16 11:54

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base

from customers.models import Client
from django.conf import settings

def load_fixture(apps, schema_editor):
    tenant = Client(domain_url='my-domain.com', 
                    schema_name='public',
                    name='Schemas Inc.',
                    paid_until='2016-12-05',
                    on_trial=False)

    tenant.save()

    tenant = Client(domain_url='lacentro.my-domain.com', # don't add your port or www here!
                    schema_name='lacentro',
                    name='lacentro',
                    paid_until='2014-12-05',
                    on_trial=True)

    tenant.save()

    tenant = Client(domain_url='ellibra.my-domain.com', # don't add your port or www here!
                    schema_name='ellibra',
                    name='el libra',
                    paid_until='2014-12-05',
                    on_trial=True)

    tenant.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('paid_until', models.DateField()),
                ('on_trial', models.BooleanField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(load_fixture)
    ]
